<?php

namespace ContainerU9dTrzh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q6kcerQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q6kcerQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q6kcerQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'notification' => ['privates', '.errored..service_locator.q6kcerQ.App\\Entity\\Notifications', NULL, 'Cannot autowire service ".service_locator.q6kcerQ": it references class "App\\Entity\\Notifications" but no such service exists.'],
            'notificationsRepository' => ['privates', 'App\\Repository\\NotificationsRepository', 'getNotificationsRepositoryService', true],
        ], [
            'notification' => 'App\\Entity\\Notifications',
            'notificationsRepository' => 'App\\Repository\\NotificationsRepository',
        ]);
    }
}
