<?php

namespace ContainerU9dTrzh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4Y6KzMGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4Y6KzMG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4Y6KzMG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BanqueDeSangController::delete' => ['privates', '.service_locator.SYi217l', 'get_ServiceLocator_SYi217lService', true],
            'App\\Controller\\BanqueDeSangController::edit' => ['privates', '.service_locator.SYi217l', 'get_ServiceLocator_SYi217lService', true],
            'App\\Controller\\BanqueDeSangController::index' => ['privates', '.service_locator.LkFPxtX', 'get_ServiceLocator_LkFPxtXService', true],
            'App\\Controller\\BanqueDeSangController::liste' => ['privates', '.service_locator.LkFPxtX', 'get_ServiceLocator_LkFPxtXService', true],
            'App\\Controller\\BanqueDeSangController::new' => ['privates', '.service_locator.LkFPxtX', 'get_ServiceLocator_LkFPxtXService', true],
            'App\\Controller\\BanqueDeSangController::show' => ['privates', '.service_locator.og211MZ', 'get_ServiceLocator_Og211MZService', true],
            'App\\Controller\\NotificationsController::delete' => ['privates', '.service_locator.q6kcerQ', 'get_ServiceLocator_Q6kcerQService', true],
            'App\\Controller\\NotificationsController::edit' => ['privates', '.service_locator.q6kcerQ', 'get_ServiceLocator_Q6kcerQService', true],
            'App\\Controller\\NotificationsController::index' => ['privates', '.service_locator.io67PaP', 'get_ServiceLocator_Io67PaPService', true],
            'App\\Controller\\NotificationsController::new' => ['privates', '.service_locator.io67PaP', 'get_ServiceLocator_Io67PaPService', true],
            'App\\Controller\\NotificationsController::show' => ['privates', '.service_locator.fHxPURc', 'get_ServiceLocator_FHxPURcService', true],
            'App\\Controller\\NotificationsController::user' => ['privates', '.service_locator.io67PaP', 'get_ServiceLocator_Io67PaPService', true],
            'App\\Controller\\NotifyAlertController::delete' => ['privates', '.service_locator.qwH0tQa', 'get_ServiceLocator_QwH0tQaService', true],
            'App\\Controller\\NotifyAlertController::edit' => ['privates', '.service_locator.qwH0tQa', 'get_ServiceLocator_QwH0tQaService', true],
            'App\\Controller\\NotifyAlertController::index' => ['privates', '.service_locator.j9Q40xJ', 'get_ServiceLocator_J9Q40xJService', true],
            'App\\Controller\\NotifyAlertController::new' => ['privates', '.service_locator.j9Q40xJ', 'get_ServiceLocator_J9Q40xJService', true],
            'App\\Controller\\NotifyAlertController::show' => ['privates', '.service_locator.cdruamx', 'get_ServiceLocator_CdruamxService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\BanqueDeSangController:delete' => ['privates', '.service_locator.SYi217l', 'get_ServiceLocator_SYi217lService', true],
            'App\\Controller\\BanqueDeSangController:edit' => ['privates', '.service_locator.SYi217l', 'get_ServiceLocator_SYi217lService', true],
            'App\\Controller\\BanqueDeSangController:index' => ['privates', '.service_locator.LkFPxtX', 'get_ServiceLocator_LkFPxtXService', true],
            'App\\Controller\\BanqueDeSangController:liste' => ['privates', '.service_locator.LkFPxtX', 'get_ServiceLocator_LkFPxtXService', true],
            'App\\Controller\\BanqueDeSangController:new' => ['privates', '.service_locator.LkFPxtX', 'get_ServiceLocator_LkFPxtXService', true],
            'App\\Controller\\BanqueDeSangController:show' => ['privates', '.service_locator.og211MZ', 'get_ServiceLocator_Og211MZService', true],
            'App\\Controller\\NotificationsController:delete' => ['privates', '.service_locator.q6kcerQ', 'get_ServiceLocator_Q6kcerQService', true],
            'App\\Controller\\NotificationsController:edit' => ['privates', '.service_locator.q6kcerQ', 'get_ServiceLocator_Q6kcerQService', true],
            'App\\Controller\\NotificationsController:index' => ['privates', '.service_locator.io67PaP', 'get_ServiceLocator_Io67PaPService', true],
            'App\\Controller\\NotificationsController:new' => ['privates', '.service_locator.io67PaP', 'get_ServiceLocator_Io67PaPService', true],
            'App\\Controller\\NotificationsController:show' => ['privates', '.service_locator.fHxPURc', 'get_ServiceLocator_FHxPURcService', true],
            'App\\Controller\\NotificationsController:user' => ['privates', '.service_locator.io67PaP', 'get_ServiceLocator_Io67PaPService', true],
            'App\\Controller\\NotifyAlertController:delete' => ['privates', '.service_locator.qwH0tQa', 'get_ServiceLocator_QwH0tQaService', true],
            'App\\Controller\\NotifyAlertController:edit' => ['privates', '.service_locator.qwH0tQa', 'get_ServiceLocator_QwH0tQaService', true],
            'App\\Controller\\NotifyAlertController:index' => ['privates', '.service_locator.j9Q40xJ', 'get_ServiceLocator_J9Q40xJService', true],
            'App\\Controller\\NotifyAlertController:new' => ['privates', '.service_locator.j9Q40xJ', 'get_ServiceLocator_J9Q40xJService', true],
            'App\\Controller\\NotifyAlertController:show' => ['privates', '.service_locator.cdruamx', 'get_ServiceLocator_CdruamxService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\BanqueDeSangController::delete' => '?',
            'App\\Controller\\BanqueDeSangController::edit' => '?',
            'App\\Controller\\BanqueDeSangController::index' => '?',
            'App\\Controller\\BanqueDeSangController::liste' => '?',
            'App\\Controller\\BanqueDeSangController::new' => '?',
            'App\\Controller\\BanqueDeSangController::show' => '?',
            'App\\Controller\\NotificationsController::delete' => '?',
            'App\\Controller\\NotificationsController::edit' => '?',
            'App\\Controller\\NotificationsController::index' => '?',
            'App\\Controller\\NotificationsController::new' => '?',
            'App\\Controller\\NotificationsController::show' => '?',
            'App\\Controller\\NotificationsController::user' => '?',
            'App\\Controller\\NotifyAlertController::delete' => '?',
            'App\\Controller\\NotifyAlertController::edit' => '?',
            'App\\Controller\\NotifyAlertController::index' => '?',
            'App\\Controller\\NotifyAlertController::new' => '?',
            'App\\Controller\\NotifyAlertController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\BanqueDeSangController:delete' => '?',
            'App\\Controller\\BanqueDeSangController:edit' => '?',
            'App\\Controller\\BanqueDeSangController:index' => '?',
            'App\\Controller\\BanqueDeSangController:liste' => '?',
            'App\\Controller\\BanqueDeSangController:new' => '?',
            'App\\Controller\\BanqueDeSangController:show' => '?',
            'App\\Controller\\NotificationsController:delete' => '?',
            'App\\Controller\\NotificationsController:edit' => '?',
            'App\\Controller\\NotificationsController:index' => '?',
            'App\\Controller\\NotificationsController:new' => '?',
            'App\\Controller\\NotificationsController:show' => '?',
            'App\\Controller\\NotificationsController:user' => '?',
            'App\\Controller\\NotifyAlertController:delete' => '?',
            'App\\Controller\\NotifyAlertController:edit' => '?',
            'App\\Controller\\NotifyAlertController:index' => '?',
            'App\\Controller\\NotifyAlertController:new' => '?',
            'App\\Controller\\NotifyAlertController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
