<?php

namespace ContainerU9dTrzh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CdruamxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cdruamx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cdruamx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'notifyAlert' => ['privates', '.errored..service_locator.cdruamx.App\\Entity\\NotifyAlert', NULL, 'Cannot autowire service ".service_locator.cdruamx": it references class "App\\Entity\\NotifyAlert" but no such service exists.'],
        ], [
            'notifyAlert' => 'App\\Entity\\NotifyAlert',
        ]);
    }
}
