<?php

namespace ContainerU9dTrzh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LkFPxtXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LkFPxtX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LkFPxtX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'banqueDeSangRepository' => ['privates', 'App\\Repository\\BanqueDeSangRepository', 'getBanqueDeSangRepositoryService', true],
        ], [
            'banqueDeSangRepository' => 'App\\Repository\\BanqueDeSangRepository',
        ]);
    }
}
