<?php

namespace ContainerU9dTrzh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotifications2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.q6kcerQ.App\Entity\Notifications' shared service.
     *
     * @return \App\Entity\Notifications
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.q6kcerQ": it references class "App\\Entity\\Notifications" but no such service exists.');
    }
}
