<?php

namespace ContainerCo9oUPy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QwH0tQaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qwH0tQa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qwH0tQa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'notifyAlert' => ['privates', '.errored..service_locator.qwH0tQa.App\\Entity\\NotifyAlert', NULL, 'Cannot autowire service ".service_locator.qwH0tQa": it references class "App\\Entity\\NotifyAlert" but no such service exists.'],
            'notifyAlertRepository' => ['privates', 'App\\Repository\\NotifyAlertRepository', 'getNotifyAlertRepositoryService', true],
        ], [
            'notifyAlert' => 'App\\Entity\\NotifyAlert',
            'notifyAlertRepository' => 'App\\Repository\\NotifyAlertRepository',
        ]);
    }
}
