<?php

namespace ContainerCo9oUPy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Io67PaPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.io67PaP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.io67PaP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'notificationsRepository' => ['privates', 'App\\Repository\\NotificationsRepository', 'getNotificationsRepositoryService', true],
        ], [
            'notificationsRepository' => 'App\\Repository\\NotificationsRepository',
        ]);
    }
}
