<?php

namespace ContainerQfaZLOl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HFr8GUGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HFr8GUG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HFr8GUG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'location' => ['privates', '.errored..service_locator.HFr8GUG.App\\Entity\\Location', NULL, 'Cannot autowire service ".service_locator.HFr8GUG": it references class "App\\Entity\\Location" but no such service exists.'],
            'locationRepository' => ['privates', 'App\\Repository\\LocationRepository', 'getLocationRepositoryService', true],
        ], [
            'location' => 'App\\Entity\\Location',
            'locationRepository' => 'App\\Repository\\LocationRepository',
        ]);
    }
}
