<?php

namespace ContainerXiOLuIE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IPRrt32Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iPRrt32' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iPRrt32'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BanqueDeSangController::delete' => ['privates', '.service_locator.SYi217l', 'get_ServiceLocator_SYi217lService', true],
            'App\\Controller\\BanqueDeSangController::edit' => ['privates', '.service_locator.SYi217l', 'get_ServiceLocator_SYi217lService', true],
            'App\\Controller\\BanqueDeSangController::index' => ['privates', '.service_locator.LkFPxtX', 'get_ServiceLocator_LkFPxtXService', true],
            'App\\Controller\\BanqueDeSangController::new' => ['privates', '.service_locator.LkFPxtX', 'get_ServiceLocator_LkFPxtXService', true],
            'App\\Controller\\BanqueDeSangController::show' => ['privates', '.service_locator.og211MZ', 'get_ServiceLocator_Og211MZService', true],
            'App\\Controller\\NotifyAlertController::delete' => ['privates', '.service_locator.qwH0tQa', 'get_ServiceLocator_QwH0tQaService', true],
            'App\\Controller\\NotifyAlertController::edit' => ['privates', '.service_locator.qwH0tQa', 'get_ServiceLocator_QwH0tQaService', true],
            'App\\Controller\\NotifyAlertController::index' => ['privates', '.service_locator.j9Q40xJ', 'get_ServiceLocator_J9Q40xJService', true],
            'App\\Controller\\NotifyAlertController::new' => ['privates', '.service_locator.j9Q40xJ', 'get_ServiceLocator_J9Q40xJService', true],
            'App\\Controller\\NotifyAlertController::show' => ['privates', '.service_locator.cdruamx', 'get_ServiceLocator_CdruamxService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\BanqueDeSangController:delete' => ['privates', '.service_locator.SYi217l', 'get_ServiceLocator_SYi217lService', true],
            'App\\Controller\\BanqueDeSangController:edit' => ['privates', '.service_locator.SYi217l', 'get_ServiceLocator_SYi217lService', true],
            'App\\Controller\\BanqueDeSangController:index' => ['privates', '.service_locator.LkFPxtX', 'get_ServiceLocator_LkFPxtXService', true],
            'App\\Controller\\BanqueDeSangController:new' => ['privates', '.service_locator.LkFPxtX', 'get_ServiceLocator_LkFPxtXService', true],
            'App\\Controller\\BanqueDeSangController:show' => ['privates', '.service_locator.og211MZ', 'get_ServiceLocator_Og211MZService', true],
            'App\\Controller\\NotifyAlertController:delete' => ['privates', '.service_locator.qwH0tQa', 'get_ServiceLocator_QwH0tQaService', true],
            'App\\Controller\\NotifyAlertController:edit' => ['privates', '.service_locator.qwH0tQa', 'get_ServiceLocator_QwH0tQaService', true],
            'App\\Controller\\NotifyAlertController:index' => ['privates', '.service_locator.j9Q40xJ', 'get_ServiceLocator_J9Q40xJService', true],
            'App\\Controller\\NotifyAlertController:new' => ['privates', '.service_locator.j9Q40xJ', 'get_ServiceLocator_J9Q40xJService', true],
            'App\\Controller\\NotifyAlertController:show' => ['privates', '.service_locator.cdruamx', 'get_ServiceLocator_CdruamxService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\BanqueDeSangController::delete' => '?',
            'App\\Controller\\BanqueDeSangController::edit' => '?',
            'App\\Controller\\BanqueDeSangController::index' => '?',
            'App\\Controller\\BanqueDeSangController::new' => '?',
            'App\\Controller\\BanqueDeSangController::show' => '?',
            'App\\Controller\\NotifyAlertController::delete' => '?',
            'App\\Controller\\NotifyAlertController::edit' => '?',
            'App\\Controller\\NotifyAlertController::index' => '?',
            'App\\Controller\\NotifyAlertController::new' => '?',
            'App\\Controller\\NotifyAlertController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\BanqueDeSangController:delete' => '?',
            'App\\Controller\\BanqueDeSangController:edit' => '?',
            'App\\Controller\\BanqueDeSangController:index' => '?',
            'App\\Controller\\BanqueDeSangController:new' => '?',
            'App\\Controller\\BanqueDeSangController:show' => '?',
            'App\\Controller\\NotifyAlertController:delete' => '?',
            'App\\Controller\\NotifyAlertController:edit' => '?',
            'App\\Controller\\NotifyAlertController:index' => '?',
            'App\\Controller\\NotifyAlertController:new' => '?',
            'App\\Controller\\NotifyAlertController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
