<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHi4scfP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHi4scfP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHi4scfP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHi4scfP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHi4scfP\App_KernelDevDebugContainer([
    'container.build_hash' => 'Hi4scfP',
    'container.build_id' => '60c71fb2',
    'container.build_time' => 1678457595,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHi4scfP');
