<?php

namespace ContainerU1P7Iby;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Dtk8JYSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Dtk8JYS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Dtk8JYS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BanqueDeSangController::delete' => ['privates', '.service_locator.SYi217l', 'get_ServiceLocator_SYi217lService', true],
            'App\\Controller\\BanqueDeSangController::edit' => ['privates', '.service_locator.SYi217l', 'get_ServiceLocator_SYi217lService', true],
            'App\\Controller\\BanqueDeSangController::index' => ['privates', '.service_locator.LkFPxtX', 'get_ServiceLocator_LkFPxtXService', true],
            'App\\Controller\\BanqueDeSangController::new' => ['privates', '.service_locator.LkFPxtX', 'get_ServiceLocator_LkFPxtXService', true],
            'App\\Controller\\BanqueDeSangController::show' => ['privates', '.service_locator.og211MZ', 'get_ServiceLocator_Og211MZService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\BanqueDeSangController:delete' => ['privates', '.service_locator.SYi217l', 'get_ServiceLocator_SYi217lService', true],
            'App\\Controller\\BanqueDeSangController:edit' => ['privates', '.service_locator.SYi217l', 'get_ServiceLocator_SYi217lService', true],
            'App\\Controller\\BanqueDeSangController:index' => ['privates', '.service_locator.LkFPxtX', 'get_ServiceLocator_LkFPxtXService', true],
            'App\\Controller\\BanqueDeSangController:new' => ['privates', '.service_locator.LkFPxtX', 'get_ServiceLocator_LkFPxtXService', true],
            'App\\Controller\\BanqueDeSangController:show' => ['privates', '.service_locator.og211MZ', 'get_ServiceLocator_Og211MZService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\BanqueDeSangController::delete' => '?',
            'App\\Controller\\BanqueDeSangController::edit' => '?',
            'App\\Controller\\BanqueDeSangController::index' => '?',
            'App\\Controller\\BanqueDeSangController::new' => '?',
            'App\\Controller\\BanqueDeSangController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\BanqueDeSangController:delete' => '?',
            'App\\Controller\\BanqueDeSangController:edit' => '?',
            'App\\Controller\\BanqueDeSangController:index' => '?',
            'App\\Controller\\BanqueDeSangController:new' => '?',
            'App\\Controller\\BanqueDeSangController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
