<?php

namespace ContainerI3QVutH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBanqueDeSang2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.og211MZ.App\Entity\BanqueDeSang' shared service.
     *
     * @return \App\Entity\BanqueDeSang
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.og211MZ": it references class "App\\Entity\\BanqueDeSang" but no such service exists.');
    }
}
