<?php

namespace ContainerI3QVutH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotifyAlertService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cdruamx.App\Entity\NotifyAlert' shared service.
     *
     * @return \App\Entity\NotifyAlert
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.cdruamx": it references class "App\\Entity\\NotifyAlert" but no such service exists.');
    }
}
